### ISSUE TITLE
Hard to extend ScriptFUSION\Mapper\Mapping

### ISSUE THREAD

**Issue by ghost** [ScriptFUSION/Mapper#1]
I'm trying to extend `Mapping` so that I can implement a *reverse* functionality, but the `$mapping` property is declared as `private`, which makes fully extending that class almost impossible. Could you please change `private` to `protected` so that child classes can change `$mapping` as they need?

Thanks!

**Comment by Bilge** [comment]
Hi @claudiobizzotto :wave: 

`$mapping` is private by design because a `Mapping` is immutable. That is, we write to `$mapping` at construct time and never again so the mapping does not change once it is created.

Could you explain in a bit more detail what you're trying to do? What would _reverse_ functionality do?

**Comment by ghost** [comment]
Actually, I was able to do the _reverse_ without directly overriding `$mapping`, but I still need to change that property from within the child class. What I need to do now is let that mapping ignore (`unset`) all keys for which there are no values. For example, imagine I have an input array like this:

``` PHP
$input = [ 'user_id' => null, 'user_name' => 'Foo' ];
```

After the mapping is done, I want the final, mapped array to _not_ contain the mapped keys that had empty values in the original array:

``` PHP
$resulting = [ 'user_name' => 'Foo' ];
```

For that to happen, `Mapping` has to unset the keys for which there are no values, i.e. it has to update its `$mapping`.

**Comment by Bilge** [comment]
I don't think what you're trying to do needs to be solved by Mapper.

``` php
array_filter([ 'user_id' => null, 'user_name' => 'Foo' ]);
```

> ['user_name' => 'Foo'];

It is important to understand that a `Mapping` is just a view of the output format you want, with instructions (also known as _strategies_), for transforming the input values. The correct way to remove a key would be to create a strategy that removes keys, not to extend the mapping. Unfortunately, it is not possible to create a strategy that would remove a key in the current version.

**Comment by claudiobizzotto** [comment]
If I do that, `Mapping` will still force a `'user_id' => 0` on the resulting array, which is what I'm trying to avoid.

**Comment by Bilge** [comment]
If your input data contains `'user_id' => null`, I do not understand how `Mapping` will force the output value to be `0` instead of `null`. Can you show me your complete input data, mapping and output data?

**Comment by ghost** [comment]
I found a way out. I'm extending `Mapper::map` and calling `array_filter` from there. Thanks for your prompt replies! :+1:
